# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Sat, 08 Oct 2022 09:56:00 +0000
*               @ALL          1
*               @user         8
