<?php
/**
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by install script
 * Date: Sat, 08 Oct 2022 09:56:00 +0000
 */
$conf['title'] = 'Flag Wiki';
$conf['lang'] = 'en';
$conf['license'] = '0';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['disableactions'] = 'backlink,index,recent,revisions,search,register,resendpwd,profile,profile_delete,edit,check,rss,subscribe,unsubscribe,source,export_raw';