# users.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Userfile
#
# Auto-generated by install script
# Date: Sat, 08 Oct 2022 09:56:00 +0000
#
# Format:
# login:passwordhash:Real Name:email:groups,comma,separated

hackergame:$2y$10$elIVR4Cxx4BIWQIZpMfkt.7wo2PAXSttRw7qrEl8B9i5srNcRDlbi:hackergame:hackergame@ustclug.org:admin,user