tags = [
    [
        "campsite",
        "pot on fire",
        "cooking",
        "1girl",
        "dark blue hair",
        "purple eyes",
        "camping clothes",
        "squatting position",
        "hands on knees",
    ],
    [
        "1girl",
        "face",
        "greenish brown long hair",
        "olive green eyes",
        "eyebrows",
        "glassy eyes",
        "big open mouth",
    ],
    [
        "aquarium",
        "2girls",
        "black long hair(left)",
        "grey cloth(left)",
        "white dress(left)",
        "act as a fish(left)",
        "blonde hair(right)",
        "red cloth(right)",
        "act as an eel(right)",
    ],
    [
        "2girls",
        "fountain",
        "blonde hair(left)",
        "red cloth(left)",
        "black long hair(right)",
        "deep blue cloth(right)",
        "grey skirt(both)",
        "left hug right",
        "left carry right",
    ],
    ["1girl", "pink hair", "yellow dress", "stand", "school hall"],
    [
        "night sky",
        "many stars",
        "2girls",
        "hold hands",
        "blonde hair(left)",
        "red cloth(left)",
        "blue hair(right)",
        "light blue cloth(right)",
    ],
    ["room", "1girl", "head on desk", "blonde hair", "comfortable"],
    [
        "1girl",
        "head out of box",
        "exciting",
        "pink hair",
        "pink cloth",
        "blue and yellow hanging decorations",
    ],
    [
        "2girls",
        "shoulder to shoulder",
        "red hair(left)",
        "horn on head(left)",
        "glassy eyes(left)",
        "pink hair(right)",
        "shy(right)",
        "surprised(right)",
    ],
    [
        "1girl",
        "face",
        "shy",
        "tightly closed eyes",
        "red hair",
        "closed mouth",
        "teardrops",
    ],
]
