#include <stdio.h>

__asm__(
    ".section "
    ".rodata"
    "\n"
    ".global "
    "g"
    "staticOutData"
    "\n"
    ".type "
    "g"
    "staticOutData"
    ", @object\n"
    ".balign "
    "16"
    "\n"
    ""
    "g"
    "staticOut"
    "Data"
    ":\n"
    ".incbin"
    " \""
    "./data/static.out"
    "\"\n"
    ".byte "
    "0\n"
    ".global "
    "g"
    "staticOutEnd"
    "\n"
    ".type "
    "g"
    "staticOutEnd"
    ", @object\n"
    ".balign 1\n"
    ""
    "g"
    "staticOut"
    "End"
    ":\n"
    ".byte "
    "1\n"
    ".global "
    "g"
    "staticOutSize"
    "\n"
    ".type "
    "g"
    "staticOutSize"
    ", @object\n"
    ".balign "
    "16"
    "\n"
    ""
    "g"
    "staticOut"
    "Size"
    ":\n"
    ".int "
    ""
    "g"
    "staticOut"
    "End"
    " - "
    ""
    "g"
    "staticOut"
    "Data"
    "\n"
    ".balign "
    "16"
    "\n"
    ".text\n");
extern const __attribute__((aligned(16))) char gstaticOutData[];
extern const __attribute__((aligned(16))) char* const gstaticOutEnd;
extern const unsigned int gstaticOutSize;
__asm__(
    ".section "
    ".rodata"
    "\n"
    ".global "
    "g"
    "dynamic0OutData"
    "\n"
    ".type "
    "g"
    "dynamic0OutData"
    ", @object\n"
    ".balign "
    "16"
    "\n"
    ""
    "g"
    "dynamic0Out"
    "Data"
    ":\n"
    ".incbin"
    " \""
    "./data/dynamic0.out"
    "\"\n"
    ".byte "
    "0\n"
    ".global "
    "g"
    "dynamic0OutEnd"
    "\n"
    ".type "
    "g"
    "dynamic0OutEnd"
    ", @object\n"
    ".balign 1\n"
    ""
    "g"
    "dynamic0Out"
    "End"
    ":\n"
    ".byte "
    "1\n"
    ".global "
    "g"
    "dynamic0OutSize"
    "\n"
    ".type "
    "g"
    "dynamic0OutSize"
    ", @object\n"
    ".balign "
    "16"
    "\n"
    ""
    "g"
    "dynamic0Out"
    "Size"
    ":\n"
    ".int "
    ""
    "g"
    "dynamic0Out"
    "End"
    " - "
    ""
    "g"
    "dynamic0Out"
    "Data"
    "\n"
    ".balign "
    "16"
    "\n"
    ".text\n");
extern const __attribute__((aligned(16))) char gdynamic0OutData[];
extern const __attribute__((aligned(16))) char* const gdynamic0OutEnd;
extern const unsigned int gdynamic0OutSize;
__asm__(
    ".section "
    ".rodata"
    "\n"
    ".global "
    "g"
    "dynamic1OutData"
    "\n"
    ".type "
    "g"
    "dynamic1OutData"
    ", @object\n"
    ".balign "
    "16"
    "\n"
    ""
    "g"
    "dynamic1Out"
    "Data"
    ":\n"
    ".incbin"
    " \""
    "./data/dynamic1.out"
    "\"\n"
    ".byte "
    "0\n"
    ".global "
    "g"
    "dynamic1OutEnd"
    "\n"
    ".type "
    "g"
    "dynamic1OutEnd"
    ", @object\n"
    ".balign 1\n"
    ""
    "g"
    "dynamic1Out"
    "End"
    ":\n"
    ".byte "
    "1\n"
    ".global "
    "g"
    "dynamic1OutSize"
    "\n"
    ".type "
    "g"
    "dynamic1OutSize"
    ", @object\n"
    ".balign "
    "16"
    "\n"
    ""
    "g"
    "dynamic1Out"
    "Size"
    ":\n"
    ".int "
    ""
    "g"
    "dynamic1Out"
    "End"
    " - "
    ""
    "g"
    "dynamic1Out"
    "Data"
    "\n"
    ".balign "
    "16"
    "\n"
    ".text\n");
extern const __attribute__((aligned(16))) char gdynamic1OutData[];
extern const __attribute__((aligned(16))) char* const gdynamic1OutEnd;
extern const unsigned int gdynamic1OutSize;
__asm__(
    ".section "
    ".rodata"
    "\n"
    ".global "
    "g"
    "dynamic2OutData"
    "\n"
    ".type "
    "g"
    "dynamic2OutData"
    ", @object\n"
    ".balign "
    "16"
    "\n"
    ""
    "g"
    "dynamic2Out"
    "Data"
    ":\n"
    ".incbin"
    " \""
    "./data/dynamic2.out"
    "\"\n"
    ".byte "
    "0\n"
    ".global "
    "g"
    "dynamic2OutEnd"
    "\n"
    ".type "
    "g"
    "dynamic2OutEnd"
    ", @object\n"
    ".balign 1\n"
    ""
    "g"
    "dynamic2Out"
    "End"
    ":\n"
    ".byte "
    "1\n"
    ".global "
    "g"
    "dynamic2OutSize"
    "\n"
    ".type "
    "g"
    "dynamic2OutSize"
    ", @object\n"
    ".balign "
    "16"
    "\n"
    ""
    "g"
    "dynamic2Out"
    "Size"
    ":\n"
    ".int "
    ""
    "g"
    "dynamic2Out"
    "End"
    " - "
    ""
    "g"
    "dynamic2Out"
    "Data"
    "\n"
    ".balign "
    "16"
    "\n"
    ".text\n");
extern const __attribute__((aligned(16))) char gdynamic2OutData[];
extern const __attribute__((aligned(16))) char* const gdynamic2OutEnd;
extern const unsigned int gdynamic2OutSize;
__asm__(
    ".section "
    ".rodata"
    "\n"
    ".global "
    "g"
    "dynamic3OutData"
    "\n"
    ".type "
    "g"
    "dynamic3OutData"
    ", @object\n"
    ".balign "
    "16"
    "\n"
    ""
    "g"
    "dynamic3Out"
    "Data"
    ":\n"
    ".incbin"
    " \""
    "./data/dynamic3.out"
    "\"\n"
    ".byte "
    "0\n"
    ".global "
    "g"
    "dynamic3OutEnd"
    "\n"
    ".type "
    "g"
    "dynamic3OutEnd"
    ", @object\n"
    ".balign 1\n"
    ""
    "g"
    "dynamic3Out"
    "End"
    ":\n"
    ".byte "
    "1\n"
    ".global "
    "g"
    "dynamic3OutSize"
    "\n"
    ".type "
    "g"
    "dynamic3OutSize"
    ", @object\n"
    ".balign "
    "16"
    "\n"
    ""
    "g"
    "dynamic3Out"
    "Size"
    ":\n"
    ".int "
    ""
    "g"
    "dynamic3Out"
    "End"
    " - "
    ""
    "g"
    "dynamic3Out"
    "Data"
    "\n"
    ".balign "
    "16"
    "\n"
    ".text\n");
extern const __attribute__((aligned(16))) char gdynamic3OutData[];
extern const __attribute__((aligned(16))) char* const gdynamic3OutEnd;
extern const unsigned int gdynamic3OutSize;
__asm__(
    ".section "
    ".rodata"
    "\n"
    ".global "
    "g"
    "dynamic4OutData"
    "\n"
    ".type "
    "g"
    "dynamic4OutData"
    ", @object\n"
    ".balign "
    "16"
    "\n"
    ""
    "g"
    "dynamic4Out"
    "Data"
    ":\n"
    ".incbin"
    " \""
    "./data/dynamic4.out"
    "\"\n"
    ".byte "
    "0\n"
    ".global "
    "g"
    "dynamic4OutEnd"
    "\n"
    ".type "
    "g"
    "dynamic4OutEnd"
    ", @object\n"
    ".balign 1\n"
    ""
    "g"
    "dynamic4Out"
    "End"
    ":\n"
    ".byte "
    "1\n"
    ".global "
    "g"
    "dynamic4OutSize"
    "\n"
    ".type "
    "g"
    "dynamic4OutSize"
    ", @object\n"
    ".balign "
    "16"
    "\n"
    ""
    "g"
    "dynamic4Out"
    "Size"
    ":\n"
    ".int "
    ""
    "g"
    "dynamic4Out"
    "End"
    " - "
    ""
    "g"
    "dynamic4Out"
    "Data"
    "\n"
    ".balign "
    "16"
    "\n"
    ".text\n");
extern const __attribute__((aligned(16))) char gdynamic4OutData[];
extern const __attribute__((aligned(16))) char* const gdynamic4OutEnd;
extern const unsigned int gdynamic4OutSize;

int main(int argc, char* argv[]) {
    FILE* fp = fopen("./temp/currentFile", "r");
    int currentFile = 0;
    if (fp != ((void*)0)) {
        fscanf(fp, "%d", &currentFile);
        fclose(fp);
    }

    fp = fopen("./temp/currentFile", "w");
    fprintf(fp, "%d", currentFile + 1);
    fclose(fp);

    if (currentFile == 0)
        printf("%s", gstaticOutData);
    else if (currentFile == 1)
        printf("%s", gdynamic0OutData);
    else if (currentFile == 2)
        printf("%s", gdynamic1OutData);
    else if (currentFile == 3)
        printf("%s", gdynamic2OutData);
    else if (currentFile == 4)
        printf("%s", gdynamic3OutData);
    else if (currentFile == 5)
        printf("%s", gdynamic4OutData);
}
